// The checkout request the createSale server action accepts from the
// browser. Only its shape is checked here, so a malformed request fails with
// a friendly message instead of a raw Postgres error. The business rules
// (quantities, discounts, notes, products) are in lib/sales/pricing.ts and
// apply to every checkout path.

import { UserFacingError } from "@/lib/action-result";
import { isPaymentMethod } from "@/lib/sales";
import {
  MAX_SALE_LINES,
  type SaleLineRequest,
  type SaleRequest,
} from "@/lib/sales/pricing";
import type { PaymentMethod } from "@/lib/types";
import { requireUuid } from "@/lib/validation";

export type CheckoutRequest = SaleRequest & {
  /**
   * Generated by the browser once per checkout and reused on retries, so a
   * retry after a lost response returns the recorded sale instead of
   * recording it twice.
   */
  saleId: string;
  paymentMethod: PaymentMethod;
};

const INVALID_SALE_MESSAGE = "Los datos de la venta no son válidos.";

function isOptional(value: unknown, type: "number" | "string") {
  return value == null || typeof value === type;
}

function parseLine(value: unknown): SaleLineRequest {
  if (!value || typeof value !== "object") {
    throw new UserFacingError(INVALID_SALE_MESSAGE);
  }
  const line = value as Record<keyof SaleLineRequest, unknown>;
  if (
    typeof line.quantity !== "number" ||
    !isOptional(line.lineDiscountCents, "number") ||
    !isOptional(line.lineDiscountReason, "string")
  ) {
    throw new UserFacingError(INVALID_SALE_MESSAGE);
  }
  return {
    productId: requireUuid(
      line.productId,
      "Uno o más productos ya no están disponibles."
    ),
    quantity: line.quantity,
    lineDiscountCents: (line.lineDiscountCents as number | null) ?? undefined,
    lineDiscountReason: line.lineDiscountReason as string | null | undefined,
  };
}

/** The request with only the fields a checkout uses, or UserFacingError. */
export function parseCheckoutRequest(input: unknown): CheckoutRequest {
  if (!input || typeof input !== "object") {
    throw new UserFacingError(INVALID_SALE_MESSAGE);
  }
  const request = input as Record<keyof CheckoutRequest, unknown>;
  if (
    !isPaymentMethod(request.paymentMethod) ||
    typeof request.saleDiscountCents !== "number" ||
    !isOptional(request.saleDiscountReason, "string") ||
    !Array.isArray(request.lines)
  ) {
    throw new UserFacingError(INVALID_SALE_MESSAGE);
  }
  if (request.lines.length > MAX_SALE_LINES) {
    throw new UserFacingError(
      `Una venta puede tener hasta ${MAX_SALE_LINES} productos distintos.`
    );
  }

  return {
    saleId: requireUuid(request.saleId, INVALID_SALE_MESSAGE),
    paymentMethod: request.paymentMethod,
    saleDiscountCents: request.saleDiscountCents,
    saleDiscountReason: request.saleDiscountReason as string | null | undefined,
    lines: request.lines.map(parseLine),
  };
}
